apiVersion: v1
kind: Service
metadata:
  name: app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Or use "elb" for Classic Load Balancer
spec:
  selector:
    app: app-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer