name: infrastructure-destroy-pipeline
run-name: Infra Destroy Pipeline
on:
  workflow_dispatch: # manual trigger

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_STS_EXTERNAL_KEY: ${{ secrets.AWS_STS_EXTERNAL_KEY }}

# aws-cli are installed on the runners by default

jobs:

#  helm-uninstall:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Generate kubectl config file
#        run: aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.AWS_EKS_CLUSTER_NAME }}
#      - name: Uninstall Helm release
#        uses: WyriHaximus/github-action-helm3@v3
#        with:
#          exec: helm uninstall ${{ vars.HELM_RELEASE_NAME }} --wait

  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init
      - name: Destroy infrastructure
        working-directory: terraform
        run: |
          terraform destroy -auto-approve \
           -var aws_key_id=$AWS_ACCESS_KEY_ID" \
           -var aws_secret_key="$AWS_SECRET_ACCESS_KEY" \
           -var aws_sts_external_id="$AWS_STS_EXTERNAL_KEY" \
           -var cluster_name="${{ vars.AWS_EKS_CLUSTER_NAME }}" \
           -var kube_namespace="${{ vars.AWS_EKS_NAMESPACE }}"
    needs: helm-uninstall

# images in ECR repo expire in 1 day and don't need to be cleaned up.